### ISSUE TITLE
[doc] ModemManager troubleshooting

### ISSUE THREAD

**Issue by LuDuda** [NordicPlayground/nRF-802.15.4-sniffer#15]
During setup of the sniffer on Linux, i found that `ModemManager` tries to write AT commands on the serial 
of the sniffer device, which caused the initialization fault. `README.md` could mentioned about this potential problem and potentially providing e.g. command to disable `ModemMenager`.

**Comment by hubertmis** [comment]
Or perhaps we could make firmware robust when it receives AT commands. If firmware is CDC ACM device, it should expect AT commands and not fail when it receives some.

**Comment by e-rk** [comment]
The problem was described in #22.
